CREATE TABLE IF NOT EXISTS colleges (
    college_id INT PRIMARY KEY AUTO_INCREMENT COMMENT '学院ID（主键）',
    college_name VARCHAR(50) NOT NULL UNIQUE COMMENT '学院名称',
    college_code VARCHAR(20) NOT NULL UNIQUE COMMENT '学院编码',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) COMMENT = '学院信息表';