CREATE TABLE IF NOT EXISTS classes (
    class_id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '班级ID（主键）',
    class_name VARCHAR(50) NOT NULL COMMENT '班级名称',
    class_code VARCHAR(20) NOT NULL UNIQUE COMMENT '班级编码',
    major_id BIGINT NOT NULL COMMENT '关联专业ID',
    college_id BIGINT NOT NULL COMMENT '关联学院ID',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (major_id) REFERENCES majors(major_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (college_id) REFERENCES colleges(college_id) ON DELETE RESTRICT ON UPDATE CASCADE
) COMMENT = '班级信息表';